### ISSUE TITLE
Create or use a streaming YouTube link for each zoomcall

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/node-github-issue-bot#7]
From https://github.com/ipfs/pm/issues/234#issuecomment-263315433

**Comment by RichardLitt** [comment]
Is this possible, @dignifiedquire?

**Comment by dignifiedquire** [comment]
@RichardLitt I am not sure what you are asking for

**Comment by RichardLitt** [comment]
Is it possible to have a consistent link to use each week? Or does it need to change each time?

**Comment by dignifiedquire** [comment]
it hast to change each week, as it is a new event

**Comment by RichardLitt** [comment]
Alright. So we'd have to use the API to get a new event each time. Good to know!

**Comment by RichardLitt** [comment]
I can't unassign myself, but I won't be getting to this soon. Closing for now.
