### ISSUE TITLE
Automatically fill HackMD notes with template

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/node-github-issue-bot#8]
The bot should automatically fill HackMD.io notepads with a template. Unfortunately, I do not think this is currently possible. 

Tracking in https://github.com/RichardLitt/generate-hackmd-links/issues/1.

**Comment by RichardLitt** [comment]
@flyingzumwalt I do not think that this is currently possible, looking at the HTML for HackMD, that it is using [CodeMirror](https://codemirror.net/) and may need to add APIs for us to do this (generate-hackmd-link is currently a hack, too, using their '/new' redirect function), and that it would be a huge amount of overhead to get working. For now, I am going to ping myself and remind myself to add the content manually.

**Comment by pmthomps** [comment]
I've got a working solution for this using websockets to hackmd.io.  I don't advertise it as the most resilient solution but it works.  Could be enough to bridge us to using peerpad.

**Comment by RichardLitt** [comment]
@pmthomps If you want to be a co-maintainer of the npm [`generate-hackmd-links`](https://github.com/RichardLitt/generate-hackmd-links) package, we could add it there, too?

**Comment by pmthomps** [comment]
@RichardLitt Cool. I'd be up for that.  Thanks!

**Comment by RichardLitt** [comment]
Cool. Open a PR to it, and we can go from there.

**Comment by victorb** [comment]
We've replaced our usage with cryptpad instead of hackmd, and current sprint-helper fills out the pad already.
